# Generated by Django 5.2.3 on 2025-07-03 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=6)),
                ('image', models.ImageField(blank=True, default='https://media.istockphoto.com/id/1459664492/vector/default-avatar-profile-user-profile-icon-profile-picture-portrait-symbol-user-member-people.jpg?s=612x612&w=0&k=20&c=NxWFtww0PspmB8u-wjHkxOyeS8aviOr9UIWTchgG8LU=', null=True, upload_to='profile')),
                ('created', models.DateField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
