# Generated by Django 5.2.3 on 2025-08-12 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='https://media.istockphoto.com/id/1459664492/vector/default-avatar-profile-user-profile-icon-profile-picture-portrait-symbol-user-member-people.jpg?s=612x612&w=0&k=20&c=NxWFtww0PspmB8u-wjHkxOyeS8aviOr9UIWTchgG8LU=', max_length=500, null=True, upload_to='profile'),
        ),
    ]
